name: Maestro iOS
description: Builds iOS app and runs Maestro on a simulator

inputs:
  expo-token:
    description: "token for Expo Application Services"
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Set up EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ inputs.expo-token }}

    - name: Install Dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Set up simulator
      uses: futureware-tech/simulator-action@v4
      with:
        model: iPhone 16 Pro Max

    - name: Build for Maestro iOS
      run: eas build --profile test -p ios --local --non-interactive --output=build.tar.gz
      shell: bash

    - name: Install app on simulator
      run: eas build:run -p ios --path build.tar.gz
      shell: bash

    - name: Run Maestro tests
      run: yarn maestro:ios:ci
      shell: bash
