name: Maestro iOS

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  maestro-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.4"
          bundler-cache: true

      - name: Set up Fastlane
        run: gem install fastlane

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Set up EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build for Maestro iOS
        run: eas build -p ios --local --non-interactive --output=build.tar.gz

      - name: Configure Maestro
        uses: dniHze/maestro-test-action@v1

      - name: Set up simulator
        uses: futureware-tech/simulator-action@v4
        with:
          model: iPhone 16 Pro Max

      - name: Install app on simulator
        run: eas build:run -p ios --path build.tar.gz

      - name: Run Maestro tests
        run: yarn maestro:ios:ci
