name: Test and Lint

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Unit Tests
        run: yarn test --watchAll=false
      - name: ESLint
        run: yarn lint
      - name: Install Expo CLI
        run: yarn global add expo-cli
      - name: Install Sharp CLI
        run: yarn global add sharp-cli@^2.1.0
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn web
          wait-on: 'http://localhost:19006'
